apiVersion: v1
kind: Service
metadata:
  name: postgres # Service name
  labels:
    app: postgres 

spec:
  type: NodePort # Service type
  ports:
    - port: 5432 # Port to run the postgres application
  selector:
    app: postgres
